language: go
go:
- 1.7.5
os:
  - linux
install:
  - go get -v -u github.com/gohugoio/hugo
script:
  - bash travis_deploy.sh
# Handle git submodules yourself
git:
  submodules: false
# Use sed to replace the SSH URL with the public URL, then initialize submodules
before_install:
  - git config --global user.email "travis@travis-ci.org"
  - git config --global user.name "Travis CI"
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init --recursive
