baseurl = "https://jose-villegas.github.io/"
title = "José Villegas"
theme = "hugo-tracks-theme"
languageCode = "en-us"
# Enable comments by entering your Disqus shortname
disqusShortname = "https-jose-villegas-github-io"
# Enable Google Analytics by entering your tracking code
googleAnalytics = "G-XJ0YK2084F"

[params]
  # Use custom.css for your custom styling
  style = "default"
  description = "Game & Graphics Programming"
  copyright = "&copy;2016 José Villegas"
  sidebarAbout = [
    ""
  ]

  # Nav links in the side bar
  [[menu.main]]
  name = "Home"
  url = "/"
  weight = 1

  [[menu.main]]
  name = "About"
  url = "about/"
  weight = 2

  [[menu.main]]
  name = "Contact"
  url = "contact/"
  weight = 3

  [params.social]
  email         = "villegasjose.gg@gmail.com"
  linkedin      = "https://www.linkedin.com/in/villegasjose"
  github        = "https://github.com/jose-villegas"
