baseurl = "https://jose-villegas.github.io/"
title = "José Villegas"
theme = "hugo-tracks-theme"
languageCode = "en-us"
# Enable comments by entering your Disqus shortname
disqusShortname = "https-jose-villegas-github-io"
# Enable Google Analytics by entering your tracking code
googleAnalytics = "UA-97909433-1"

[params]
  # Use custom.css for your custom styling
  style = "default"
  description = "Graphics & Game Programming"
  copyright = "&copy;2016 José Villegas"
  sidebarAbout = [
    ""
  ]

  # Nav links in the side bar
  [[params.navlinks]]
  name = "Home"
  url = ""

  # [[params.navlinks]]
  # name = "About"
  # url = "about/index"

  # [[params.navlinks]]
  # name = "Contact"
  # url = "contact/index"

  [params.social]
  email         = "villegasjose.gg@gmail.com"
  linkedin      = "https://www.linkedin.com/in/villegasjose"
  github        = "https://github.com/jose-villegas"
